StrangerThings/StrangerThings/Models/Character.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StrangerThings.Models
{
    //This model is based off Characters table in the StrangerThings database
    [Table("Characters")]
    public class Character
    {
        //Declare the primary key
        [Key]
        public int CharacterID { get; set; }

        //Declare the other attributes
        [DisplayName("First Name")]
        public string CharacterFirstName { get; set; }
        [DisplayName("Last Name")]
        public string CharacterLastName { get; set; }
        [DisplayName("Description")]
        public string CharacterDescription { get; set; }
        public string Hometown { get; set; }
        [DisplayName("Year of Birth")]
        public int YearOfBirth { get; set; }
        [DisplayName("Photo Location")]
        public string PhotoLocation { get; set; }
        public string Actor { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public string Quote { get; set; }

        //Collection of Questions (foreign key relationship)
        public ICollection<Question> Questions { get; set; }
    }
}

StrangerThings/StrangerThings/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StrangerThings.DAL;
using StrangerThings.Models;

namespace StrangerThings.Controllers
{
    public class CharactersController : Controller
    {
        private StrangerThingsContext db = new StrangerThingsContext();

        // GET: Characters
        public ActionResult Index()
        {
            return View(db.Characters.ToList());
        }

        // GET: Characters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }

            //Creates a list of questions to be passed to the viewbag so the character page can show questions associated with the character
            var Questions = new List<Question>();

            //If the question is related to the character, add to the list
            foreach (var q in db.Questions)
            {
                if (q.CharacterID == id)
                {
                    Questions.Add(q);
                }
            }

            ViewBag.Questions = Questions;

            return View(character);
        }

        // GET: Characters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CharacterID,CharacterFirstName,CharacterLastName,CharacterDescription,Hometown,YearOfBirth,PhotoLocation,Actor,Gender,Occupation,Quote")] Character character)
        {
            if (ModelState.IsValid)
            {
                db.Characters.Add(character);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(character);
        }

        // GET: Characters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CharacterID,CharacterFirstName,CharacterLastName,CharacterDescription,Hometown,YearOfBirth,PhotoLocation,Actor,Gender,Occupation,Quote")] Character character)
        {
            if (ModelState.IsValid)
            {
                db.Entry(character).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = character.CharacterID });
            }
            return View(character);
        }

        // GET: Characters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Character character = db.Characters.Find(id);
            db.Characters.Remove(character);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StrangerThings/StrangerThings/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StrangerThings.DAL;
using StrangerThings.Models;

namespace StrangerThings.Controllers
{
    public class QuestionsController : Controller
    {
        private StrangerThingsContext db = new StrangerThingsContext();

        // GET: Questions
        //Passing in an id so the index will only show question related with the character.
        [Authorize]
        public ActionResult Index(int? id)
        {
            //If no ID is passed, a bad request page is shown
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Create a new list of questions to pass into the index view 
            var questions = new List<Question>();

            //Go through all the questions in the database and only add questions related to the character
            foreach(var q in db.Questions)
            {
                if(q.CharacterID == id)
                {
                    questions.Add(q);
                }
            }

            //Add the character to the viewbag and the character full name to the viewbag
            ViewBag.Character = db.Characters.Find(id);
            ViewBag.CharacterFullName = ViewBag.Character.CharacterFirstName + " " + ViewBag.Character.CharacterLastName;

            return View(questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index", new { id = question.CharacterID });
        }

        // GET: Questions/Create
        public ActionResult Create(int? id)
        {
            //If no ID is passed, a bad request page is shown
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Find the character and add it to the viewbag
            ViewBag.Character = db.Characters.Find(id);
            ViewBag.CharacterFullName = ViewBag.Character.CharacterFirstName + " " + ViewBag.Character.CharacterLastName;

            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = question.CharacterID });
            }

            ViewBag.CharacterID = new SelectList(db.Characters, "CharacterID", "CharacterFirstName", question.CharacterID);
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            //Add the character to the viewbag and the character full name to the viewbag
            ViewBag.Character = db.Characters.Find(question.CharacterID);
            ViewBag.CharacterFullName = ViewBag.Character.CharacterFirstName + " " + ViewBag.Character.CharacterLastName;

            return View(question);
        }

        // GET: Questions/EditAnswer/5
        public ActionResult EditAnswer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            //Find the character and add it to the viewbag
            ViewBag.Character = db.Characters.Find(question.CharacterID);
            ViewBag.CharacterFullName = ViewBag.Character.CharacterFirstName + " " + ViewBag.Character.CharacterLastName;

            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(question).State = EntityState.Modified;
                db.Questions.Find(question.QuestionID).QuestionDescription = question.QuestionDescription;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = question.CharacterID });
            }
            ViewBag.CharacterID = new SelectList(db.Characters, "CharacterID", "CharacterFirstName", question.CharacterID);
            return View(question);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAnswer(int id, string answer)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Find(id).Answer = answer;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = db.Questions.Find(id).CharacterID });
            }

            return View(db.Questions.Find(id));
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            //Add the character to the viewbag and the character full name to the viewbag
            ViewBag.Character = db.Characters.Find(question.CharacterID);
            ViewBag.CharacterFullName = ViewBag.Character.CharacterFirstName + " " + ViewBag.Character.CharacterLastName;

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = question.CharacterID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StrangerThings/StrangerThings/Views/Characters/Create.cshtml
@model StrangerThings.Models.Character

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Character</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CharacterFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CharacterDescription, new { @class = "form-control", rows = "10", style = "width:100%;" })
                @Html.ValidationMessageFor(model => model.CharacterDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hometown, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hometown, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hometown, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhotoLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Actor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quote, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-red" />
                @Html.ActionLink("Back to Characters", "Index", null, new { @class = "btn btn-red" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StrangerThings/StrangerThings/Views/Characters/Delete.cshtml
@model StrangerThings.Models.Character

@{
    ViewBag.CharacterFullName = @Model.CharacterFirstName + " " + @Model.CharacterLastName;
    ViewBag.Title = "Delete " + ViewBag.CharacterFullName;
}  

<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb layout">
        <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "redtext" })</li>
        <li class="breadcrumb-item">@Html.ActionLink("Characters", "Index", "Characters", null, new { @class = "redtext" })</li>
        <li class="breadcrumb-item">@Html.ActionLink((string)ViewBag.CharacterFullName, "Details", "Characters", new { id = Model.CharacterID }, new { @class = "redtext" })</li>
        <li class="breadcrumb-item active" aria-current="page">Delete</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-4 col-sm-6">
        @*Display the character image*@
        <img class="img-responsive img-rounded" src="@Model.PhotoLocation" />
    </div>

    <div class="col-md-8 col-sm-6">
       
        <h2>Are you sure you want to delete @ViewBag.CharacterFullName?</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-red" /> |
                    @Html.ActionLink("Back to Character", "Details", new { id = Model.CharacterID }, new { @class="btn btn-red" })
                </div>
            }
    </div>
</div>

StrangerThings/StrangerThings/Views/Characters/Details.cshtml
@model StrangerThings.Models.Character  

@{
    ViewBag.Title = Model.CharacterFirstName + ' ' + Model.CharacterLastName;
}

<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb layout">
        <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "redtext" })</li>
        <li class="breadcrumb-item">@Html.ActionLink("Characters", "Index", "Characters", null, new { @class="redtext" })</li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-4 col-sm-6">
        @*Display the character image*@
        <img class="img-responsive img-rounded" src="@Model.PhotoLocation" />
    </div>
    <div class="col-md-8 col-sm-6">
        @*Show the first name and last name for the character*@
        <h2>@Model.CharacterFirstName @Model.CharacterLastName</h2>

        @*Show the character description*@
        <p>@Model.CharacterDescription</p>

        @*Display character attributes*@
        <p><b>Year of Birth:</b> @Model.YearOfBirth</p>

        <p><b>Gender:</b> @Model.Gender</p>

        <p><b>Hometown:</b> @Model.Hometown</p>

        <p><b>Occupation:</b> @Model.Occupation</p>

        <p><b>Actor:</b> @Model.Actor</p>

        <p><b>Quote:</b> @Model.Quote</p>


        @*Display options to edit, delete, or go back to character list*@
        @Html.ActionLink("Edit", "Edit", "Characters", new { id = Model.CharacterID }, new { @class = "redtext" }) |
        @Html.ActionLink("Delete", "Delete", "Characters", new { id = Model.CharacterID }, new { @class = "redtext" }) |
        @Html.ActionLink("Back to Characters", "Index", "Characters", null, new { @class = "redtext" })

        <!--Navigates to the Index method in the Questions controller.  Passes in the character id of the current character-->
        <h3>@Html.ActionLink(@Model.CharacterFirstName + " " + @Model.CharacterLastName + " FAQs", "Index", "Questions", new { id = Model.CharacterID }, new { @class = "btn btn-red" })</h3>
    </div>
</div>

StrangerThings/StrangerThings/Views/Characters/Edit.cshtml
@model StrangerThings.Models.Character

@{
    ViewBag.CharacterFullName = @Model.CharacterFirstName + " " + @Model.CharacterLastName;
    ViewBag.Title = "Edit " + ViewBag.CharacterFullName;
}

<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb layout">
        <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "redtext" })</li>
        <li class="breadcrumb-item">@Html.ActionLink("Characters", "Index", "Characters", null, new { @class = "redtext" })</li>
        <li class="breadcrumb-item">@Html.ActionLink((string)ViewBag.CharacterFullName, "Details", "Characters", new { id = Model.CharacterID }, new { @class = "redtext" })</li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-4 col-sm-6">
        @*Display the character image*@
        <img class="img-responsive img-rounded" src="@Model.PhotoLocation" />
    </div>

    <div class="col-md-8 col-sm-6">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CharacterID)

                <div class="form-group">
                    @Html.LabelFor(model => model.CharacterFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CharacterFirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CharacterFirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CharacterLastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CharacterLastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CharacterLastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CharacterDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.CharacterDescription, new { @class = "form-control", rows = "10", style = "width:100%;" })
                        @Html.ValidationMessageFor(model => model.CharacterDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Hometown, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Hometown, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Hometown, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhotoLocation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhotoLocation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhotoLocation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Actor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Actor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Actor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quote, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Quote, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quote, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-red" />
                        @Html.ActionLink("Ignore Changes", "Details", new { id = Model.CharacterID }, new { @class = "btn btn-red" })
                    </div>
                </div>
            </div>
        }
        
    </div>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StrangerThings/StrangerThings/Views/Characters/Index.cshtml
@model IEnumerable<StrangerThings.Models.Character>

@{
    ViewBag.Title = "Characters";

    //Put the Model of characters into a list so we can iterate through it using a for loop
    var list = Model.ToList();
}

<h2>Characters</h2>

<!--Dropdown menu allows user to select a character without scrolling through the whole page-->

<div class="row">
    <div class="dropdown col-xs-9 col-sm-9 col-md-9">
        <button class="btn btn-red dropdown-toggle" type="button" data-toggle="dropdown">
            Select Character
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <!--Add a list item for each character in the model.  Link goes to character detail view-->
            @foreach (var item in list)
            {
                <li><a href="@Url.Action("Details", new { id = item.CharacterID })">@item.CharacterFirstName @item.CharacterLastName</a></li>
            }
        </ul>
    </div>

    <div class="col-xs-3 col-sm-3 col-md-3">
        <p class="pull-right">@Html.ActionLink("Create New", "Create", "Characters", null, new { @class = "btn btn-red" })</p>
    </div>
</div>

<!--For each character, display the character name and image.  For loop used instead of for each loop so I can add a new row every four characters-->
@for (int i = 0; i < list.Count; i++)
{
    //Create a new bootstrap row every four rows
    if (i % 4 == 0)
    {
        @:<div class="row">
    }

    <div class="col-md-3">
        <!--Clicking on the image or the name will go to the details view-->
        <a href="@Url.Action("Details", "Characters", new { id = list[i].CharacterID })">

            <!--Show the first name and last name for the character-->
            <h3>@Html.DisplayFor(modelItem => list[i].CharacterFirstName) @Html.DisplayFor(modelItem => list[i].CharacterLastName)</h3>

            <!--Display the character image-->
            <img class="img-responsive img-thumbnail" src="@Html.DisplayFor(modelItem => list[i].PhotoLocation)" />
        </a>
    </div>

    //End the bootstrap row every four rows.
    if ((i + 1) % 4 == 0 || (i + 1) == list.Count)
    {
        @:</div>
    }
}